sudo: required
services:
  - docker

before_install:
  - docker build -t renngeschaft/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run renngeschaft/react-test npm test -- --coverage

after_success:
  - docker build -t renngeschaft/multi-client ./client
  - docker build -t renngeschaft/multi-nginx ./nginx
  - docker build -t renngeschaft/multi-server ./server
  - docker build -t renngeschaft/multi-worker ./worker
  # Log into the Docker cli.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to hub.docker.com.
  - docker push renngeschaft/multi-client
  - docker push renngeschaft/multi-nginx
  - docker push renngeschaft/multi-server
  - docker push renngeschaft/multi-worker
